### ISSUE TITLE
SERVICE_NOT_AVAILABLE Error

### ISSUE THREAD

**Issue by stripathi669** [inloop/easygcm#13]
Hi, I have am getting Post-registration message: Error :SERVICE_NOT_AVAILABLE continuously. I have followed instruction on the readme file. 

The android Documentation says:

   When the application receives a com.google.android.c2dm.intent.REGISTRATION intent with the error extra set as SERVICE_NOT_AVAILABLE, it should retry the failed operation (register or unregister).

I guess this is already implemented in the package. Any guess to why am i getting this error ?

Moreover, I checked that you didn't mention to add anything to Manifest (such as GCM C2Dm actions). Are they not required ?

**Comment by martinadamek** [comment]
I believe it is caused by issue #12 and the reason is that manifest merging is not working correctly in certain situations (investigating now). All that GCM related stuff is defined in AndroidManifest.xml of the library and apparently it is failing during the build phase sometimes. I am pretty sure this can be close once issue #12 will be resolved.
