### ISSUE TITLE
Re-register immediately after app update

### ISSUE THREAD

**Issue by destil** [inloop/easygcm#15]
GCM registration ID is only valid for one version of the app. It's a good practice to listen to `MY_PACKAGE_REPLACED` Broadcast receiver and re-register immediately after the update. Otherwise GCM messages will not come until user launches to app.

**Comment by adrien-aubel** [comment]
+1!

**Comment by DanielNovak** [comment]
+1 on this. I will try to make a pull request. Here is some background on this https://medium.com/@murki/gcm-push-notifications-registration-done-right-7aba759d1d55. 
The registration can change after updating the app and in that case the GCM messages will stop to work until the user starts the app again. I do think that this is a rare case and the registration ID does not change after updating in normal cases - but this needs to be addressed anyway.

**Comment by DanielNovak** [comment]
I have made a proof-of-concept commit. I need to finish some details - the most important one is to prevent starting the GCM registration process if it's already running. This can happen if you update the application and start it right after updating. You will get the MY_PACKAGE_REPLACED broadcast and the first activity will start the registration too. I think I will go with a singleton for the GCMHelper so that I can track the registration state (or I will just use a static attribute).
ETA: 24 hours

**Comment by destil** [comment]
@DanielNovak Great work, thanks! I posted about your library and it's spreading on G+ like a virus :) Can you also merge pull requests or @martinadamek has to do it? There is enough of them for a new version.

**Comment by DanielNovak** [comment]
I can do it, I just pinged @martinadamek so he can take a quick look. I am not sure about https://github.com/inloop/easygcm/pull/8 - this a controversial change, so I don't know if we will add this into the next release :-). The rest will be merged and a new version released as soon as possible.

**Comment by martinadamek** [comment]
Yes, let's put as much as possible into new release.
